fullnameOverride: ""
nameOverride: ""

global:
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext: {}
  pullPolicy: IfNotPresent

innspire:
  # Trace, Debug, Information, Warning, Error, Critical, None
  logLevel: "Information"


innspireWebsite:
  enabled: true
  image:
    repository: ghcr.io/innspire/innspirewebsite
    tag: "latest"
  ingress:
    enabled: false
    hosts:
    - example.com
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  resources: {}
  pdb:
    create: false
    minAvailable: 1
    maxUnavailabe: ""
  nodeSelector: {}
  affinity: {}
  tolerations: []
  probes:
    enabled: true
  logLevel: "Information"

innspireWebAPI:
  enabled: true
  image:
    repository: ghcr.io/innspire/innspirewebapi
    tag: "latest"
  ingress:
    enabled: false
    hosts:
    - api.example.com
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  resources: {}
  pdb:
    create: false
    minAvailable: 1
    maxUnavailabe: ""
  nodeSelector: {}
  affinity: {}
  tolerations: []
  probes:
    enabled: true
  logLevel: "Information"
  apiUrl: https://api.example.com
  apiHostname: api.example.com
  jwtSecret: ""
  jwtTokenExpiry: 10080