fullnameOverride: ""
nameOverride: ""

global:
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext: {}

innspire:
  # Will be generated if not provided.
  apiSecret: ""
  # Trace, Debug, Information, Warning, Error, Critical, None
  logLevel: "Information"


innspireWebsite:
  enabled: true
  image:
    repository: ghcr.io/innspire/innspirewebsite
    pullPolicy: IfNotPresent
    tag: "latest"
  ingress:
    enabled: false
    hosts:
    - example.com
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  resources: {}
  pdb:
    create: false
    minAvailable: 1
    maxUnavailabe: ""
  nodeSelector: {}
  affinity: {}
  tolerations: []
  logLevel: "Information"