apiVersion: v1
kind: Secret
metadata:
  name: {{ include "innspire.fullname" . }}-innspire-api-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "innspire.labels" . | nindent 4 }}
    app.kubernetes.io/component: "innspirewebsite"
data:
  API_SECRET: {{ .Values.innspire.apiSecret | default (randAlphaNum 32) | b64enc | quote }}