apiVersion: v1
kind: Service
metadata:
  name: {{ include "innspire.fullname" . }}-innspireadminconsole
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "innspire.labels" . | nindent 4 }}
    app.kubernetes.io/component: "innspireadminconsole"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "innspire.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "innspireadminconsole"