apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "innspire.fullname" . }}-innspirewebapi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "innspire.labels" . | nindent 4 }}
    app.kubernetes.io/component: "innspirewebapi"
data:
  LOGLEVEL: {{ .Values.innspireWebAPI.logLevel }}
  API_URL: {{ .Values.innspireWebAPI.apiUrl }}
  API_HOSTNAME: {{ .Values.innspireWebAPI.apiHostname }}
