apiVersion: v1
kind: Secret
metadata:
  name: {{ include "innspire.fullname" . }}-innspirewebapi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "innspire.labels" . | nindent 4 }}
    app.kubernetes.io/component: "innspirewebapi"
data:
  JWT_SECRET: {{ .Values.innspireWebAPI.jwtSecret | default (randAlphaNum 96) | b64enc | quote }}
  POSTGRES_URI: {{ .Values.innspireWebAPI.postgresUri | b64enc | quote }}
