apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "innspire.fullname" . }}-innspirewebsite
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "innspire.labels" . | nindent 4 }}
    app.kubernetes.io/component: "innspirewebsite"
data:
  LOGLEVEL: {{ .Values.innspireWebsite.logLevel }}
  API_URL: http://{{ include "innspire.fullname" . }}-innspirewebapi:8080