{{- if .Values.innspireWebsite.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "innspire.fullname" . }}-innspirewebsite
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "innspire.labels" . | nindent 4 }}
    app.kubernetes.io/component: "innspirewebsite"
spec:
  {{- if not .Values.innspireWebsite.autoscaling.enabled }}
  replicas: {{ .Values.innspireWebsite.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "innspire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "innspirewebsite"
  template:
    metadata:
      labels:
        {{- include "innspire.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "innspirewebsite"
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: innspirewebsite
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          image: "{{ .Values.innspireWebsite.image.repository }}:{{ .Values.innspireWebsite.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
            - name: metrics
              containerPort: 9123
              protocol: TCP
          {{- if .Values.innspireWebsite.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 15
            periodSeconds: 10
          {{- end }}
          resources:
            {{- toYaml .Values.innspireWebsite.resources | nindent 12 }}
          env:
            - name: LOGLEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "innspire.fullname" . }}-innspirewebsite
                  key: LOGLEVEL
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "innspire.fullname" . }}-innspirewebsite
                  key: API_URL
      {{- with .Values.innspireWebsite.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.innspireWebsite.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.innspireWebsite.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}