name: docker-build-main
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GHCR
        shell: bash
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/innspire --username ${{ github.actor }} --password-stdin
      - name: Install PyBump
        run: |
          python3 -m pip install pybump
        shell: bash
      - name: Helm Chart
        shell: bash
        run: |
          version=$(pybump get --file ./Chart.yaml)
          helm package . --version $version
          helm push innspire-$version.tgz ghcr.io/innspire 
